package dk.lundogbendsen.javase8advanced.threads.ex05.threadgroups;

/*
 * Demonstrerer hvordan en trådgruppe kan opfange de Exceptions, som
 * dens Threads ikke får håndterer (dvs. uncaught exceptions). Under normale
 * omstændigheder vil en trådgruppe blot udskrive den fejl der opstod og
 * derefter dræbe tråden der lavede den. I dette eksempel får vi istedet for
 * mulighed for selv at bestemme hvad der skal gøres ved ikke-håndterede fejl.
 * PRØV fx at udkommentere linie 28 og indkommentere linie 29
 */
public class ThreadGroupAsExceptionHandler
{

  public static void main(final String[] args)
  {

    // Vi laver først en UnhandledExceptionListener, som definerer hvad
    // der skal ske, hvis der forekommer ikke-håndterede Exceptions
    UnhandledExceptionListener listener = new UnhandledExceptionListener()
    {
      @Override
      public void unhandledException(final Thread t, final Throwable e)
      {
        System.out.println("Unhandled Exception experienced");
        System.out.println("   Generated by the Thread: " + t.getName());
        System.out.println("   Exception is: " + e.toString());
      }
    };

    // Vi laver nu en ExceptionForwardingThreadGroup, og registrerer vores
    // UnhandledExceptionListener som lytter på ikke-håndterede fejl, som
    // genereres af tråde i tråd-gruppen. Bemærk at vi i øvrigt upcaster til
    // ThreadGroup for at bruge den som en hver anden trådgruppe.
    // PRØV fx at udkommentere linie 28 og indkommentere linie 29
    ThreadGroup group = new ExceptionForwardingThreadGroup("Special-gruppe", listener);
    // ThreadGroup group = new ThreadGroup( "Almindelig gruppe" );

    // Vi laver nu en ny tråd i trådgruppen, og sikrer os at dens run(
    // )-metode vil
    // smide en fejl (her en ArithmeticException da man ikke kan dele med
    // 0).
    Thread tråd = new Thread(group, "Fejlbehæftet tråd")
    {
      @Override
      public void run()
      {
        int a = 12 / 0;
        System.out.println(a);
      }
    };

    System.out.println("Vi starter nu den fejlbehæftede tråd");
    tråd.start();
    try
    {
      Thread.sleep(2000);
    }
    catch (InterruptedException e)
    {
    }
    System.out.println("På dette tidspunkt må fejlen være opstået");
  }
}